# Generated by Django 5.0.6 on 2024-07-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('Job', '0002_alter_jobpost_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(default='Select Your Company', on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='education',
            field=models.ForeignKey(default='Highest Qualification', on_delete=django.db.models.deletion.CASCADE, to='Job.education'),
        ),
    ]
