# Generated by Django 5.0.6 on 2024-07-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_alter_jobpost_company_alter_jobpost_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=50, unique=True, verbose_name='Salary Range')),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.ForeignKey(default='10000-20000', on_delete=django.db.models.deletion.CASCADE, to='Job.salaryrange'),
        ),
    ]
