# Generated by Django 5.0.6 on 2024-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_salaryrange_alter_jobpost_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrange',
            name='range',
        ),
        migrations.AddField(
            model_name='salaryrange',
            name='salary_range',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
