# Generated by Django 5.0.7 on 2024-08-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_disablejob_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
