# Generated by Django 5.0.6 on 2024-07-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApplicant', '0002_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
