# Generated by Django 5.0.6 on 2024-07-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApplicant', '0003_alter_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='about',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker_profile',
            name='insta',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
