# Generated by Django 5.0.6 on 2024-07-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_chatroom_chatmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
