# Generated by Django 5.0.7 on 2024-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0003_frequently_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequently_asked',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
