# Generated by Django 5.0.7 on 2024-08-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontrol', '0005_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='icon',
        ),
    ]
